// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configures what happens when an automated approval reviewer backend fails
 * before returning a valid decision.
 */
export type ApprovalsReviewerFailurePolicy = "deny" | "defer_to_user";
